import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

const InterSas = Inter({
  variable: "--font-body-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Barbearia do Victor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR" className={`${InterSas.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#E7D8BF]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
